# Generated by Django 5.2.7 on 2025-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
